basePath: /api/v1
definitions:
  contracts.AddressResponse:
    properties:
      city:
        type: string
      number:
        type: integer
      street:
        type: string
      zip_code:
        $ref: '#/definitions/contracts.ZipCodeResponse'
    type: object
  contracts.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  contracts.BurnActionResponse:
    properties:
      burn_id:
        type: string
      state:
        type: string
    type: object
  contracts.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  contracts.PhoneResponse:
    properties:
      country_code:
        type: string
      number:
        type: string
    type: object
  contracts.ProfileResponse:
    properties:
      address:
        $ref: '#/definitions/contracts.AddressResponse'
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone:
        $ref: '#/definitions/contracts.PhoneResponse'
      user_name:
        type: string
      user_type:
        type: string
    type: object
  contracts.ResetPasswordRequest:
    properties:
      confirm_password:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - password
    type: object
  contracts.ZipCodeResponse:
    properties:
      value:
        type: string
    type: object
  geojson.GeoJsonFeature:
    properties:
      geometry:
        $ref: '#/definitions/geojson.Geometry'
      properties: {}
      type:
        type: string
    type: object
  geojson.Geometry:
    properties:
      coordinates:
        items:
          type: number
        type: array
      type:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is the api for Fire Watch Mobile Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FireWatch API
  version: "1.0"
paths:
  /auth/forgot_password:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: Email address associated with the account
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Request a Password Reset
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: Login Payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/contracts.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.AuthResponse'
      summary: Authenticate with account
      tags:
      - Auth
  /auth/refresh_tokens:
    get:
      consumes:
      - application/json
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: JWT token to be refreshed
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/contracts.AuthResponse'
      summary: Refresh Tokens
      tags:
      - Auth
  /auth/reset_password:
    post:
      consumes:
      - application/json
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: A unique token sent to the user's email for password reset
        in: query
        name: forgot_token
        required: true
        type: string
      - description: Reset Password Payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/contracts.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password reset successfully
          schema:
            type: string
      summary: Reset Password
      tags:
      - Auth
  /auth/signUp:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - in: formData
        name: city
        required: true
        type: string
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: first_name
        required: true
        type: string
      - in: formData
        name: last_name
        required: true
        type: string
      - in: formData
        name: nif
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: phone_code
        required: true
        type: string
      - in: formData
        name: phone_number
        required: true
        type: string
      - in: formData
        name: street
        required: true
        type: string
      - in: formData
        name: street_port
        required: true
        type: integer
      - in: formData
        name: user_name
        required: true
        type: string
      - in: formData
        name: zip_code
        required: true
        type: string
      - description: User avatar
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/contracts.AuthResponse'
      summary: Create an Account
      tags:
      - Auth
  /burn:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: search burn title
        in: query
        name: search
        required: true
        type: string
      - description: search by burn state
        in: query
        name: state
        required: true
        type: string
      - description: search by an inital date
        in: query
        name: start_date
        required: true
        type: string
      - description: search by an end date
        in: query
        name: end_date
        required: true
        type: string
      - default: 1
        description: view page
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: number of returned elements
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geojson.GeoJsonFeature'
      security:
      - Bearer: []
      summary: Fetch burns
      tags:
      - Burn
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - in: formData
        name: has_backup_team
        required: true
        type: boolean
      - in: formData
        name: init_date
        required: true
        type: string
      - in: formData
        name: initial_propose
        required: true
        type: string
      - in: formData
        name: lat
        required: true
        type: number
      - in: formData
        name: lon
        required: true
        type: number
      - in: formData
        name: reason
        required: true
        type: string
      - in: formData
        name: title
        required: true
        type: string
      - in: formData
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/contracts.BurnActionResponse'
      security:
      - Bearer: []
      summary: Create an Burn Request
      tags:
      - Burn
  /burn/{burnId}:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - description: Fetch the burn by id
        in: query
        name: burnId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geojson.GeoJsonFeature'
      security:
      - Bearer: []
      summary: Fetch Burn By Id
      tags:
      - Burn
  /burn/reasons:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      security:
      - Bearer: []
      summary: Burn Available Reasons
      tags:
      - Burn
  /burn/states:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      security:
      - Bearer: []
      summary: Burn Available States
      tags:
      - Burn
  /burn/types:
    get:
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      security:
      - Bearer: []
      summary: Burn Available Types
      tags:
      - Burn
  /profile:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      - in: formData
        name: city
        required: true
        type: string
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: phone_code
        required: true
        type: string
      - in: formData
        name: phone_number
        required: true
        type: string
      - in: formData
        name: street
        required: true
        type: string
      - in: formData
        name: street_port
        required: true
        type: integer
      - in: formData
        name: user_name
        required: true
        type: string
      - in: formData
        name: zip_code
        required: true
        type: string
      - description: User avatar
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/contracts.ProfileResponse'
      security:
      - Bearer: []
      summary: Update Profile Information
      tags:
      - Profile
  /whoami:
    get:
      consumes:
      - multipart/form-data
      parameters:
      - description: some description
        in: header
        name: accept-language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.ProfileResponse'
      security:
      - Bearer: []
      summary: Fetch Profile Information
      tags:
      - Profile
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
