basePath: /api/v1
definitions:
  contracts.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  contracts.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is the api for Fire Watch Mobile Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FireWatch API
  version: "1.0"
paths:
  /auth/forgot_password:
    get:
      parameters:
      - description: Email address associated with the account
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Request a Password Reset
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/contracts.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.AuthResponse'
      summary: Authenticate with account
      tags:
      - Auth
  /auth/signUp:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: city
        required: true
        type: string
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: first_name
        required: true
        type: string
      - in: formData
        name: last_name
        required: true
        type: string
      - in: formData
        name: nif
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: phone_code
        required: true
        type: string
      - in: formData
        name: phone_number
        required: true
        type: string
      - in: formData
        name: street
        required: true
        type: string
      - in: formData
        name: street_port
        required: true
        type: integer
      - in: formData
        name: zip_code
        required: true
        type: string
      - description: User avatar
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.AuthResponse'
      summary: Create an Account
      tags:
      - Auth
swagger: "2.0"
